application: haldean-cypherd
version: 1
runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: /.*
  script: cypherd.app

libraries:
- name: jinja2
  version: '2.6'
- name: markupsafe
  version: '0.15'
